name: VibeScript Governance

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  vibe-check:
    name: Vibe Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for git diff

      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect package manager
        id: detect-pm
        run: |
          if [ -f "pnpm-lock.yaml" ]; then
            echo "manager=pnpm" >> $GITHUB_OUTPUT
            echo "install=pnpm install --frozen-lockfile" >> $GITHUB_OUTPUT
            echo "run=pnpm" >> $GITHUB_OUTPUT
          elif [ -f "yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_OUTPUT
            echo "install=yarn install --frozen-lockfile" >> $GITHUB_OUTPUT
            echo "run=yarn" >> $GITHUB_OUTPUT
          else
            echo "manager=npm" >> $GITHUB_OUTPUT
            echo "install=npm ci" >> $GITHUB_OUTPUT
            echo "run=npm run" >> $GITHUB_OUTPUT
          fi

      - name: Setup pnpm
        if: steps.detect-pm.outputs.manager == 'pnpm'
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            ~/.pnpm-store
            node_modules
          key: ${{ runner.os }}-${{ steps.detect-pm.outputs.manager }}-${{ hashFiles('**/package-lock.json', '**/pnpm-lock.yaml', '**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.detect-pm.outputs.manager }}-

      - name: Install dependencies
        run: ${{ steps.detect-pm.outputs.install }}

      - name: Set base ref for comparison
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VIBE_BASE_REF=origin/${{ github.base_ref }}" >> $GITHUB_ENV
          else
            echo "VIBE_BASE_REF=HEAD~1" >> $GITHUB_ENV
          fi

      - name: Run Vibe Check (guard + checker)
        run: ${{ steps.detect-pm.outputs.run }} vibe:check

      - name: Upload reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vibe-reports
          path: .vibe/reports/
          retention-days: 7
