name: VibeScript Governance

on:
  pull_request:
    branches: [main, master]
  push:
    branches: [main, master]

jobs:
  vibe-check:
    name: Vibe Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history required for git diff

      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.base_ref }}:refs/remotes/origin/${{ github.base_ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 9

      - name: Get pnpm store directory
        shell: bash
        run: echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Set base ref for comparison
        run: |
          if [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "VIBE_BASE_REF=origin/${{ github.base_ref }}" >> $GITHUB_ENV
          else
            echo "VIBE_BASE_REF=HEAD~1" >> $GITHUB_ENV
          fi

      - name: Run Vibe Check (guard + checker)
        run: pnpm vibe:check

      - name: Upload reports on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: vibe-reports
          path: .vibe/reports/
          retention-days: 7
